### ISSUE TITLE
Navbar element effect

### ISSUE THREAD

**Issue by HrutvikKhatkar** [HrutvikKhatkar/Restaurant_website_HacktoberFest#2]

**Comment by pranav-lad** [comment]
Hey @HrutvikKhatkar, I would love to work on this issue. Kindly consider assigning it to me
here's my profile https://linktr.ee/pranavlad

**Comment by pccoe-acm** [comment]
@pranav-lad ok i have assigned this to you fix it and attach screen shot

**Comment by pranav-lad** [comment]
Hey @pccoe-acm ,
I have added navbar element effect 
checkout PR: https://github.com/pccoe-acm-hacktoberfest-2023/Restaurant_website_HacktoberFest/pull/13

Below are screen shots:
Before element effect
![image](https://github.com/pccoe-acm-hacktoberfest-2023/Restaurant_website_HacktoberFest/assets/87913792/10138146-0113-477a-be05-af404222fdcc)

After element effect
![image](https://github.com/pccoe-acm-hacktoberfest-2023/Restaurant_website_HacktoberFest/assets/87913792/344e97f1-58de-4fcd-b75b-c4774315002e)

**Comment by pranav-lad** [comment]
hey @HrutvikKhatkar ,
kindly consider reviewing and accepting the PR for issue #13,
