### ISSUE TITLE
Add Hover effect

### ISSUE THREAD

**Issue by mith105** [HrutvikKhatkar/Restaurant_website_HacktoberFest#9]
## Issue Description:
  When hovering over cards, the border color should change to a specific color and opacity should decrease. I am willing to contribute this issue.

  Proposed Solution:
  Use the following CSS code to achieve the desired effect:
```
.wcu-card:hover {
    border-color: rgb(216, 164, 42);
    opacity: 0.7;
  }
```

  Explanation:
  - The .wcu-card:hover selector targets elements with the class "wcu-card" when they are hovered over.
  - The "border-color" property sets the border color to RGB(216, 164, 42) when hovering over the card.
  - The "opacity" property decreases the opacity to 0.7, making the card slightly transparent on hover.

**Comment by Girish345** [comment]
I want to work on that can you please assign it to me

**Comment by mith105** [comment]
Assign to me

**Comment by pccoe-acm** [comment]
@mith105 ok fix this and attach screen shot once done

**Comment by mr-osiris** [comment]
@mith105 i have added hover and popup effects to the card and raised pr for it.
